version: '3'
services:
  mysql:
    image: mysql:8.0.21
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tony
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: